language: node_js
node_js:
  - lts/*
install:
  - npm install # npm ci
script:
  - npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  target-branch: master
  repo: shownoso/shownoso.github.io
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: WOtN3tKgEh4wyF1IxAGytMBLfjoSN5cKp7VB7gBhCmxWYS0hilhM+XKnIobAaXAt3NdBeJlEsGBW1b1m9laTHGyJgrEsmFIYX4tquHzEoYrIYhHIENZLL6EWzudmS+pW5KGCYxKYGn+46yFUH6h9+R6xpoMYI4GRQflEyk/DpaDLDIgObyOf+Fy2Z3sRdO40IM2fbhx+znETcu3Jje57xntr3X8JbukpEZQEXhO04xCZ3AqokH4SfPOk1hqSsojT3VJyP+mm4aQEdMYn6zinR3PdWknCKCbFG0V/Y3rHDBIGcm4vM0D+D8UWUsXFpBpi6+6nzFCRHGpx5LiHp6qsdThBGevxHDiqlpdcHN+hGw8U7XIJ4Y1QfLODgHC3xY8Z9Ehwg2MKAxRDuXme4G9vyhY1ftzGcQb15HTu0a7a+9FoSv8vJLy0dAMlYgLqFYYDwISjXcJ4ApTObM0/JED3EnFpeRt+zJwo5Mm2DNipH4xk5Kg0y4VzpkofOb75RHhBa9SyVYnjxkz+kMrrukAgG3uBBvY+G9eMah7kI4LIjCzj4Fn7FKcjYX0a0xjdVWViVij/u0EvQt4y5arXJNARFskbEAvG6to92lFs10pIOeXJ4dIZBQ8NYn5btpAuMhJiTLcfvuHridRJntPc8hrea8ID8YCGfcQ/5Fp8jhzVi9M=