language: node_js
node_js:
- lts/*
branchs:
  only:
  - master
cache:
  directories:
  - "node_modules"
install:
- npm install
script:
- npm run docs:build
after_success:
- ssh $REMOTE_USER "echo 'travis build done!' "
before_install:
- openssl aes-256-cbc -K $encrypted_800bf27b8633_key -iv $encrypted_800bf27b8633_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: $REMOTE_IP
env:
  global:
  - secure: WOtN3tKgEh4wyF1IxAGytMBLfjoSN5cKp7VB7gBhCmxWYS0hilhM+XKnIobAaXAt3NdBeJlEsGBW1b1m9laTHGyJgrEsmFIYX4tquHzEoYrIYhHIENZLL6EWzudmS+pW5KGCYxKYGn+46yFUH6h9+R6xpoMYI4GRQflEyk/DpaDLDIgObyOf+Fy2Z3sRdO40IM2fbhx+znETcu3Jje57xntr3X8JbukpEZQEXhO04xCZ3AqokH4SfPOk1hqSsojT3VJyP+mm4aQEdMYn6zinR3PdWknCKCbFG0V/Y3rHDBIGcm4vM0D+D8UWUsXFpBpi6+6nzFCRHGpx5LiHp6qsdThBGevxHDiqlpdcHN+hGw8U7XIJ4Y1QfLODgHC3xY8Z9Ehwg2MKAxRDuXme4G9vyhY1ftzGcQb15HTu0a7a+9FoSv8vJLy0dAMlYgLqFYYDwISjXcJ4ApTObM0/JED3EnFpeRt+zJwo5Mm2DNipH4xk5Kg0y4VzpkofOb75RHhBa9SyVYnjxkz+kMrrukAgG3uBBvY+G9eMah7kI4LIjCzj4Fn7FKcjYX0a0xjdVWViVij/u0EvQt4y5arXJNARFskbEAvG6to92lFs10pIOeXJ4dIZBQ8NYn5btpAuMhJiTLcfvuHridRJntPc8hrea8ID8YCGfcQ/5Fp8jhzVi9M=
  - secure: M3X+jBvEkmtTB54A9HIfNd/rXW7rcsns7HyVtIi/st+uXf0jy7DF+oaPKNAnflR8/gltoOSH7D6S8JztD6NvbxMLJLjUIwBajSlYdXrqdDQXyQXPRzRdI3EI3Zvr0w9bhIQh76vyWwVYkb0wNiyQlRdh84t4q+4L+YsVTTBNR/zjKzPDBNSuJ1SGYBRxQ0wxWh7skHG2OpDR/JTWjO9ECcFWLZfRkHCtu6LeE+EWjgMCPDNDblsIY0rmethXDieRahS4fKsoOANVwjuLxBSHNpzot2dlg7q5hdINw5O7B9aeddg8c3g1Du1aNaDa2nfSVRnumqkq28k7i800EmyJX9GkPXk72eb/jMry0PPvLfYUJV3DCxo1mhO82ebJVa5Hmx2K/f0Pdvmp8kDOOGc5RjglMpzdscd4/ZHtOO1UE24R+R/gD2Z/t8NGC4myMj8ZzT+M8uVvSGOG5elT2Rx/jw6kMTXXnZK5tXw/gcs/RV+R07OcSHAqAHVjXnvdbSr0sXCdPLHEYAzSMyQHWOZPwmN5Ludfh3LHMrDvLiQrJ9OxSETbXGDOouOcf1Cc2XIRI44d8GUZ77PS4rEYaT2QoyXVup0qeCGqRNv5M95eFuJHIkTWJNyMgNSVIYObJOc2kOG04Yyu3+IACZgCLZ5wg+iAJbZY8CplSgNkimmvmxc=
  - secure: Pk8lRqPq1Lr+qbx4FytNoILpIuNm03b9ExFAu5nhGzC0VOBArnuhCYWkelokO0pd53oiOPNOeNfPzJ29kjbIegv6RF72ZE+JOsEQwD3+el98tiixOrFS4eX8itgNrn1aSyYV9WpywSzoR+LrPhTxa3pVujcFJVd3VeFDW61guYi4JkpVOOYeYFisVda4y12/umpIOtTtFz/kHLPPE3l82ZNAo8SgUaSR9BCp36b4TDpFI33hD37rQfsqsRmJsx8jPM+adXFSd177RsjR63O9ukS8aKUHF9ZCuFVPsbDtwCdA38+DrcT6XySCBaCCGFmy8caNVBLuguCDX9VoXGZ1gkqxwy5m6BTkvfGdC7Ucyyo36RdiyLA0PPus6C1yUKv/5X/GdlLX+jswvF4uhTDjX9F8/W+wNuMgtFfkoqA/80/scc5RZnnfamO4SuqUOksTBcyJrO0bQlKzlkNkp89HASI1fF7IBTmDQQ94edjCbqfk2GzRZdHlyuqYz/FbL7MVQ4wZKVzADD41z0lI4+ktlXTK6c/6uU0PIXd0DCfKTfg9uEgc3uzqwkZru9ZIhYy6qRRo2/CFbDwb208tsvCYRYTRfBQiNRiuFeEpHUGuTaV/An72EQyJDmvVctfkiKpxXlaHgFEiKKsZk0ox3FseCFE82Qv60l7O5FtMcGMfR/I=
